/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'selectedColor' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'selectedSize' : string,
}
export interface OfferBanner {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'description' : string,
  'discountPercent' : bigint,
  'imageUrl' : [] | [string],
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentStatus' : string,
  'createdAt' : Time,
  'totalAmount' : bigint,
  'buyer' : Principal,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : bigint,
  'deliveryEstimate' : string,
  'inStock' : boolean,
  'originalPrice' : bigint,
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'category' : string,
  'colors' : Array<string>,
  'discountedPrice' : bigint,
  'returnable' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBanner' : ActorMethod<[OfferBanner], bigint>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBanner' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getActiveBanners' : ActorMethod<[], Array<OfferBanner>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[], bigint>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBanner' : ActorMethod<[bigint, OfferBanner], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];